  op SDN_ : StrMap -> Recursive .
  ops SW SWP C C0 : -> Recursive .
  ops SW0 : -> String .
  ops Help Up Up0 : -> Channel .
  op init : -> TraceNodes .

  var Sws : StrMap .

  eq getRecPol(SW) = "(f=3) . (pt=1) . (pt<-2)" ; SW o+
                      "(f=3) . (pt=1)" ; ( (Help ! "one") ; SW ) o+
                      (Up ? "one") ; SWP .
  eq getRecPol(SWP) = "zero" ; SWP .
  eq getRecPol(C) = (Help ? "one") ; ( (Up ! "one") ; C ) .
