  op SDN_ : StrMap -> Recursive .
  ops SW SWP C1 C2 : -> Recursive .
  ops SW0 : -> String .
  ops Up1 Help1 Help2 Up2 : -> Channel .
  op init : -> TraceNodes .

  var Sws : StrMap .

  eq getRecPol(SW) = (Help1 ! "one1") ; SW o+
                      (Up1 ? "one1") ; SWP .
  eq getRecPol(SWP) = "zero" ; SWP o+
                      "(f=4) . (pt=3)" ; ((Help2 ! "one2") ; SWP) o+
                      (Up2 ? "one2") ; SW .

  eq getRecPol(C1) = (Help1 ? "one1") ; ( (Up1 ! "one1") ; C1 ) .
  eq getRecPol(C2) = (Help2 ? "one2") ; ( (Up2 ! "one2") ; C2 ) .
